### DISCUSSION TITLE
<rh-card>: borderless variant

### DISCUSSION THREAD

**Discussion by marionnegp** [RedHat-UX/red-hat-design-system#1468] [Ideas]
A borderless version of card has come up as a need in several designs. The padding would be removed too.

Benefits:
- Less visual noise when there are many cards or when there is a lot of content in each card
- Could help move us away from having really boxy layouts
- Can be used in a dynamic grid
- Card is easier to use than simple divs in Drupal or groups in Figma. It keeps things more consistent.

Would there be any issues to creating this as a new variant or card pattern?

**Comment by bennypowers** [comment]
This sounds like a useful addition. I'm not sure this needs any code changes in RHDS. We can [accomplish this with a single CSS rule (codepen)](https://codepen.io/bennyp/pen/LYadbaE?editors=1100) (ok, i guess it's really 3 rules if you desugar the nesting)

```css
rh-card.borderless {
  &::part(container) { border: 0; }   
  &::part(header),
  &::part(footer) { margin: 0; }
  &::part(body) { margin-inline: 0; }
}
```

I'd be in favour of documenting this as an approved pattern.
