### DISCUSSION TITLE
Pattern: Table Accordion

### DISCUSSION THREAD

**Discussion by bennypowers** [RedHat-UX/red-hat-design-system#1606] [Ideas]
@zeroedin 's fine work on ux-dot has me thinking about potential pattern definitions, for example: The Table Accordion (i.e. accordion panel containing a table)

In this demo screenshot, the `Methods` accordion panel demonstrates the pattern as i have it in mind, while the `Events` panel is the current state, without customization.

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/be3833dc-9716-454b-bb96-e8ac92561151)

Here are the css changes used to make that screenshot, essentially, we have to remove table margins and adjust heading padding to match accordion

```css

rh-accordion-panel rh-table {
  margin: 0;
  & :is(th, td) {
    padding-inline-start: var(--rh-space-lg, 24px);
  }
}
```

Further iterations we might consider:
- replace the accordion header contents with the table heading row whenever the accordion panel is expanded, although setting up aria links between them might be difficult and perhaps even prohibited
- require the table to be one color palette off from the accordion, so if the accordion is `lightest,` the table should be `lighter`

WDYT @marionnegp @coreyvickery @adamjohnson ?
