### DISCUSSION TITLE
Theming, Context, and Broadcast: From PFE to RHDS

### DISCUSSION THREAD

**Discussion by heyMP** [RedHat-UX/red-hat-design-system#306] [General]
In `rh-footer` we transitioned from PFE's color context variables (i.e. the broadcast variables) to using our own `rh-` prefixed vars with design token fallbacks.  This begs the question of if / how we should be tying our colors into PFE's broadcast variables at all.

### Example

Before

```css
a {
  color: var(--pfe-broadcasted--link, #06c);
  text-decoration: var(--pfe-broadcasted--link-decoration, none);
}
a:hover {
  color: var(--pfe-broadcasted--link--hover, #004080);
  text-decoration: var(--pfe-broadcasted--link-decoration--hover, underline);
}
a:focus {
  color: var(--pfe-broadcasted--link--focus, #004080);
  text-decoration: var(--pfe-broadcasted--link-decoration--focus, underline);
}
a:visited {
  color: var(--pfe-broadcasted--link--visited, #6753ac);
  text-decoration: var(--pfe-broadcasted--link-decoration--visited, none);
}
```

After

```css
rh-footer a {
  color: var(--rh-color-link-inline-on-light, var(--rh-color-blue-500, #06c));
  text-decoration: none;
}
rh-footer a:hover {
  color: var(--rh-color-link-inline-hover-on-light, var(--rh-color-blue-600, #004080));
  text-decoration: underline;
}
rh-footer a:focus {
  color: var(--rh-color-link-inline-hover-on-light, var(--rh-color-blue-600, #004080));
  text-decoration: underline;
}
rh-footer a:visited {
  color: var(--rh-color-link-inline-visited-on-dark, var(--rh-color-purple-300, #a18fff));
  text-decoration: none;
}
```

Results in us loosing correct styling in dark contexts:

![Screen Shot 2022-05-24 at 8 30 34 AM](https://user-images.githubusercontent.com/3428964/170038112-c85bde6f-2be4-407d-a1ad-3315ef410b59.png)

### Background

PFE relies on the following block of code to switch the color of text and links based on color context:

@patternfly/pfe-styles/pfe-context.css

```css
.on-dark {
  --pfe-broadcasted--text: var(--pfe-theme--color--text--on-dark, #fff);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted--on-dark, #d2d2d2);
  --pfe-broadcasted--link: var(--pfe-theme--color--link--on-dark, #73bcf7);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover--on-dark, #bee1f4);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus--on-dark, #bee1f4);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited--on-dark, #bee1f4);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration--on-dark, none);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover--on-dark, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus--on-dark, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited--on-dark, none);
  --context: dark;
}

.on-saturated {
  --pfe-broadcasted--text: var(--pfe-theme--color--text--on-saturated, #fff);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted--on-saturated, #d2d2d2);
  --pfe-broadcasted--link: var(--pfe-theme--color--link--on-saturated, #fff);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover--on-saturated, #fafafa);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus--on-saturated, #fafafa);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited--on-saturated, #d2d2d2);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration--on-saturated, underline);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover--on-saturated, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus--on-saturated, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited--on-saturated, underline);
  --context: saturated;
}

.on-light {
  --pfe-broadcasted--text: var(--pfe-theme--color--text, #151515);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted, #6a6e73);
  --pfe-broadcasted--link: var(--pfe-theme--color--link, #06c);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover, #004080);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus, #004080);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited, #6753ac);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration, none);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited, none);
  --context: light;
}

.surface--darker {
  --pfe-broadcasted--text: var(--pfe-theme--color--text--on-dark, #fff);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted--on-dark, #d2d2d2);
  --pfe-broadcasted--link: var(--pfe-theme--color--link--on-dark, #73bcf7);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover--on-dark, #bee1f4);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus--on-dark, #bee1f4);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited--on-dark, #bee1f4);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration--on-dark, none);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover--on-dark, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus--on-dark, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited--on-dark, none);
  --context: dark;
  background-color: #3c3f42;
  color: var(--pfe-broadcasted--text, #3c3f42);
}

.surface--accent {
  --pfe-broadcasted--text: var(--pfe-theme--color--text--on-saturated, #fff);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted--on-saturated, #d2d2d2);
  --pfe-broadcasted--link: var(--pfe-theme--color--link--on-saturated, #fff);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover--on-saturated, #fafafa);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus--on-saturated, #fafafa);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited--on-saturated, #d2d2d2);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration--on-saturated, underline);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover--on-saturated, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus--on-saturated, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited--on-saturated, underline);
  --context: saturated;
  background-color: #004080;
  color: var(--pfe-broadcasted--text, #3c3f42);
}

.surface--complement {
  --pfe-broadcasted--text: var(--pfe-theme--color--text--on-saturated, #fff);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted--on-saturated, #d2d2d2);
  --pfe-broadcasted--link: var(--pfe-theme--color--link--on-saturated, #fff);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover--on-saturated, #fafafa);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus--on-saturated, #fafafa);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited--on-saturated, #d2d2d2);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration--on-saturated, underline);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover--on-saturated, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus--on-saturated, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited--on-saturated, underline);
  --context: saturated;
  background-color: #002952;
  color: var(--pfe-broadcasted--text, #3c3f42);
}

.surface--base {
  --pfe-broadcasted--text: var(--pfe-theme--color--text, #151515);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted, #6a6e73);
  --pfe-broadcasted--link: var(--pfe-theme--color--link, #06c);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover, #004080);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus, #004080);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited, #6753ac);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration, none);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited, none);
  --context: light;
  background-color: #f0f0f0;
  color: var(--pfe-broadcasted--text, #3c3f42);
}

.surface--lighter {
  --pfe-broadcasted--text: var(--pfe-theme--color--text, #151515);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted, #6a6e73);
  --pfe-broadcasted--link: var(--pfe-theme--color--link, #06c);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover, #004080);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus, #004080);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited, #6753ac);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration, none);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited, none);
  --context: light;
  background-color: #f0f0f0;
  color: var(--pfe-broadcasted--text, #3c3f42);
}

.surface--lightest {
  --pfe-broadcasted--text: var(--pfe-theme--color--text, #151515);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted, #6a6e73);
  --pfe-broadcasted--link: var(--pfe-theme--color--link, #06c);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover, #004080);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus, #004080);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited, #6753ac);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration, none);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited, none);
  --context: light;
  background-color: #fff;
  color: var(--pfe-broadcasted--text, #3c3f42);
}

/*# sourceMappingURL=pfe-context.css.map */
```

**Comment by bennypowers** [comment]
NB: consensus so far is to eventually move the context code altogether into RHDS

**Reply by brianferry** [reply]
I second this, I think we'll need it in RHDS since some of these variables will probably be different between the projects.

**Comment by bennypowers** [comment]
As a stopgap solution, we can copy those context styles into a shared constructible stylesheet object and have all our components use it

**Comment by bennypowers** [comment]
We're going to cover this in a sync meeting at some point soon, so this is a drop jumping the gun, but nonetheless writing it out helps me organize my thoughts. 

From where I'm sitting, it's not clear what the concept of `broadcast` adds to our design system, beyond what CSS does implicitly via inheritance and the cascade. CSS Custom Properties always inherit (and thereby pierce shadow boundaries), so any variable set on a node inherits to all it's children until and unless a child overrides that value. When I think about what our needs are (theming, colour context), it seems that inheritance and the cascade are enough.

So I'd prefer to see components use design tokens like `--rh-color-brand-red-lightest` and `--rh-color-text-primary` (which would resolve to `--rh-color-text-primary-on-{dark|light}`, depending), rather than introduce an intermediary step with the `broadcast` terminology.

**Reply by bennypowers** [reply]
I'm playing with some ideas as part of `<rh-cta>` migration.

@markcaron @heyMP do you think that tokens which assign a value to `--rh-context-light-*` and `--rh-context-dark-*` work?
```css
/* defaults */
--rh-context-dark-color-text: var(--rh-color-text-primary-on-dark, #ffffff);
--rh-context-dark-color-text-muted: var(--rh-color-text-secondary-on-dark, #aaaaaa);
--rh-context-dark-color-text-link: var(--rh-color-interactive-blue-lighter, #73bcf7);
--rh-context-dark-color-text-link-hover: var(--rh-color-interactive-blue, #0066cc);
--rh-context-dark-color-text-link-focus: var(--rh-color-interactive-blue, #0066cc);
--rh-context-dark-color-text-link-visited: var(--rh-color-interactive-blue, #0066cc);
--rh-context-light-color-text: var(--rh-color-text-primary-on-light, #151515);
--rh-context-light-color-text-muted: var(--rh-color-text-secondary-on-light, #6c6c6c);
--rh-context-light-color-text-link: var(--rh-color-interactive-blue, #0066cc);
--rh-context-light-color-text-link-hover: var(--rh-color-interactive-blue-darker, #004080);
--rh-context-light-color-text-link-focus: var(--rh-color-interactive-blue-darker, #004080);
--rh-context-light-color-text-link-visited: var(--rh-color-interactive-purple-darker, #6753ac);
```

My working assumption is that `broadcast` means "assign context-based values to well-known properties for the purposes of styling light DOM children"

**Reply by bennypowers** [reply]
@coreyvickery The (partial) source for above is:
```yml
context:
  dark:
    color:
      text:
        _:
          type: color
          value: '{color.text.primary.on.dark}'
        muted:
          type: color
          value: '{color.surface.light}' #f0f0f0, closest to #d2d2d2 from pf
        link:
          _:
            type: color
            value: '{color.interactive.blue.lighter}'
          hover:
            type: color
            value: '{color.interactive.blue._}'
          focus:
            type: color
            value: '{color.interactive.blue._}'
          visited:
            type: color
            value: '{color.interactive.blue._}'
```
NOTE that this breaks the mold of having `-on-dark` in a suffix position, that's because I'm interpreting `-broadcast` here as `--rh-context-${whatev}` (see previous comment)
