### ISSUE TITLE
[bug]: `<rh-tabs>` margin-line when vertical

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1299]
tabs should never have a margin-inline (inset) when also vertical.

Fix:
```css
:host(:is([centered]:not([vertical]), [box="inset"]:not([vertical]))) [part="tabs"] {
  margin-inline: var(--rh-tabs-inset, var(--_inset-inline-margin, auto));
}
```

this was exposed by change up to demos that allows these properties to be easily added: https://deploy-preview-1291--red-hat-design-system.netlify.app/elements/tabs/demo/color-context/
