### ISSUE TITLE
[feat] desaturated <rh-cta> variants

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1391]
### Description

The [desaturated `<rh-cta>` variants](https://ux.redhat.com/elements/call-to-action/style/#white-variants) is needed for dark and saturated surfaces. This variant is already available in the [Figma library](https://www.figma.com/file/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?type=design&node-id=26%3A770&mode=design&t=9OCkPKNDrIjKtaNx-1).

### Suggested solution

![image (5)](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/a3e949e7-e85b-4f9a-b06e-1b8d0b45afbb)

Will also need to update the CTA docs to say that it's available for saturated surfaces too

**Comment by zeroedin** [comment]
Is this maybe `<rh-cta variant="white">` and then opposite`<rh-cta variant="black">` as well for lighter saturated color backgrounds.

**Comment by markcaron** [comment]
@zeroedin or perhaps a `variant="desaturated"` that responds automatically to `<rh-surface>` and color context?

**Comment by bennypowers** [comment]
Here's an example of what I mean by that

https://codepen.io/bennyp/pen/abrqXVG?editors=1100

```html
<rh-card color-palette="darkest">
  <h2 slot="header">Desaturated Calls to Action</h2>
  <p>Desaturated is a theme (i.e. a pattern) applied to certain CTAs</p>
  <rh-cta class="desaturated"><a href="#">Default</a></rh-cta>
  <rh-cta class="desaturated" icon="play-circle"><a href="#">Default Video</a></rh-cta>
  <rh-cta class="desaturated" variant="primary"><a href="#">Primary</a></rh-cta>
  <rh-cta class="desaturated" variant="primary" icon="play-circle"><a href="#">Video</a></rh-cta>
</rh-card>
```

```css
.desaturated {
  --rh-color-text-primary-on-dark: var(--rh-color-surface-darkest);
  --rh-color-brand-red-on-light: var(--rh-color-surface-lightest);
  --rh-color-brand-red-dark: var(--rh-color-gray-40);
  --rh-color-interactive-blue-lighter: var(--rh-color-surface-lightest);
  --rh-color-interactive-blue-lightest: var(--rh-color-gray-40);
}
```
