### ISSUE TITLE
[docs]: `<rh-card>` variants demo css

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1403]
When styling off of the `[data-demo]` attribute this works for the standalone demo link ie (https://ux.redhat.com/elements/card/demo/variants/) and the local dev server (localhost:8000/elements/card/demo/variants/) but will not work when rendered in the playground element on the overview page.

Question to answer for possible solution:
If possible can we modify the playground to pass a class on it's `body` tag in the iframe so we can apply a combined selector such as the following:

```css
.playground-demo,
[data-demo="rh-card"] {
    padding: 0.5em;
    display: grid;
    gap: 1em;
    grid-template-columns: repeat(auto-fit, minmax(360px, 1fr));
    grid-auto-columns: 1fr;
  }
 ```
