### ISSUE TITLE
[bug] `<rh-card>` body slot does not allow styling headers

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1522]
`<rh-card>` default body slot does not allow styling headers due to `inherit !important` when combined with other slotted content.  

Documentation also states it is [ok to add headers](https://ux.redhat.com/elements/card/style/#body) to the body slot.  The [layout section](https://ux.redhat.com/elements/card/style/#layout) shows an example of this use case showing mixed content.

Therefore we'd assume we'd want  the font `Red Hat Display` for those headers.

However we use the rules:

```css
::slotted(*) {
  font-family: inherit !important;
  line-height: inherit !important;
}

::slotted(:is(h1, h2, h3, h4, h5, h6)) {
  font-size: inherit !important;
}
```

Because these look upwards and we can't style children from `:part(body)` you can only manipulate 1 `font-size` or `font-family` for the entire slot.  This doesn't work when you have mixed content `h3 + p` as an example:

https://codepen.io/zeroedin/pen/eYoLMYQ

The fix here might necessitate a breaking change?  I've set Charmander as milestone, unless we come up with a way to release a fix prior to that.  

This bug was discovered by @max-messmer when implementing the designs for My Red Hat Elements.  Thanks for bringing it to our attention.
