### ISSUE TITLE
[docs] groundwork for version dropdown

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1542]
It **should** hit a endpoint stores data for the version dropdown that is available at `ux.redhat.com/versions.json` that way future versions will always target the latest.  Older versions after 2.0 is release would be at a path such as `ux.redhat.com/v1/`.

```json
{
  "versions": {
     "v1": "https://ux.redhat.com/v1",
     "v2 : "https://ux.redhat.com/"
  }
}
```

Then build the dropdown with javascript using the name: url key value.

**Comment by hellogreg** [comment]
Related: https://github.com/RedHat-UX/red-hat-design-system/issues/1485

**Comment by zeroedin** [comment]
For PFE we are deploying these sites to two different domains then there is a redirects in netlify.toml

```
[[redirects]]
  from = '/v1/*'
  to = 'https://release-v1--patternfly-elements.netlify.app/:splat'
  status = 200
  force = true

[[redirects]]
  from = '/v2/*'
  to = 'https://release-v2--patternfly-elements.netlify.app/:splat'
  status = 200
  force = true
```

There was talk awhile back about moving the `ux.` domain to netlify is this still possible @markcaron ?  If so would make versioning the site much like we do in patternfly elements easier.  

Otherwise we'll have to modify CI to checkout and build these docs subdirectories, although I figure we'll run into issues with node versions on build doing so.

**Comment by bennypowers** [comment]
So I think the moving parts here are:
1. deploying release tags reliably
2. redirecting from those release tag branches in the netlify config
3. adding those links to the page

Here follows a lightly edited stream of consciousness on how we might solve those

## Config-only approach
As of [2020](https://answers.netlify.com/t/wildcard-branches-for-branch-deploys/25647) netlify doesn't support wildcards in the branch deploy filter. However, it appears we can do the [filtering ourselves in netlify.toml](https://docs.netlify.com/configure-builds/ignore-builds/). So I'd like to suggest we try enabling branch deploys for *all* branches, then add this config (or something like it, this is draft pseudocode) to netlify.toml

```toml
[context.branch-deploy]
  ignore = "node -e 'process.exit(process.env.BRANCH.match(/staging\/|v\d\.\d\.\d/) ? 0 : 1)'"
```

That regexp

You can check that code with this:

```
nvm install v18
BRANCH="staging/steven" node -e 'process.exit(process.env.BRANCH.match(/staging\/|v\d\.\d\.\d/) ? 0 : 1)'"
BRANCH="fix/whatever" node -e 'process.exit(process.env.BRANCH.match(/staging\/|v\d\.\d\.\d/) ? 0 : 1)'"
BRANCH="video-killed-the-radio-star" node -e 'process.exit(process.env.BRANCH.match(/staging\/|v\d\.\d\.\d/) ? 0 : 1)'"
BRANCH="v3.2.1" node -e 'process.exit(process.env.BRANCH.match(/staging\/|v\d\.\d\.\d/) ? 0 : 1)'"
```

The advantages here are that it's fairly automatic.
The major disadvantage is that we'd get unique deploys for *each* release, even patch releases, and we'd get granular urls like `deploy-v1-2-3-red-hat-design-system.netlify.app`, when what we would prefer would be to create or update deploys for each major version like `release-v1-red-hat-design-system.netlify.app`
We'd also have to manually manage the redirects in netlify.toml

So I don't think this approach is good for version deploys, but i do think it's good for `staging/*` deploys.

## CLI approach
So I think a better approach would be similar to what we did with pfe. We set up a github actions workflow to trigger on release, 

```yaml
on:
  release:
    types: 
      - published
```

we could then do some light scripting to get the major version from the release tag
```yaml
jobs:
  publish-versioned-docs: 
    runs-on: "ubuntu-latest"
    steps:
      - name: Get major version
        uses: actions/github-script@v7
        id: version
        env:
          RELEASE_VERSION: ${{ github.event.release.tag-name }}
        with:
          script: return process.env.RELEASE_VERSION.split('.').shift();
```
Then use that to set the deploy alias for netlify CLI

```yaml
      - name: Publish versioned docs to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_ALIAS: release-${{steps.version.outputs.result}}
        run: >
              npx netlify-cli deploy
              --dir _site
              --alias $NETLIFY_DEPLOY_ALIAS
```
I still think we'll need to manually set up the redirect paths, but for now we can just paste in v1-v9

and we can backfill v1 manually by checking out the latest v1 tag locally, manually building, and deploying with an alias.
