### ISSUE TITLE
[docs] page styles affecting demos

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1793]
### Description

Context demos are getting page styles, which can have unexpected effects

this patch demonstrates how to fix the problem in dev tools

```css

/* Element | https://deploy-preview-1792--red-hat-design-system.netlify.app/elements/accordion/demo/color-context/ */

#provider {
  height: 100%;
  height: auto;
}

/* styles.css | https://deploy-preview-1792--red-hat-design-system.netlify.app/styles/dev-server/styles.css */

@layer layout {
  rh-context-demo {
    /* height: auto; */
    height: 100%;
  }
}

/* Element | https://deploy-preview-1792--red-hat-design-system.netlify.app/elements/accordion/demo/color-context/ */

body > main:nth-child(1) > rh-context-demo:nth-child(1) {
  height: 100%;
}

/* Element | https://deploy-preview-1792--red-hat-design-system.netlify.app/elements/accordion/demo/color-context/ */

body > main:nth-child(1) {
  height: 100%;
}

/* Element | https://deploy-preview-1792--red-hat-design-system.netlify.app/elements/accordion/demo/color-context/ */

body {
  height: 100%;
}

/* Element | https://deploy-preview-1792--red-hat-design-system.netlify.app/elements/accordion/demo/color-context/ */

html {
  height: 100%;
}
```

### Screenshots

![image](https://github.com/user-attachments/assets/e2c4efea-5fee-4474-b76b-ad47d51b7587)

### Steps to reproduce

See https://ux.redhat.com/elements/accordion/demo/color-context/

### Expected behaviour

Demos should have the bare minimum of styles applied - basically just `global.css` and maybe some very basic page typography.

### Operating System (OS)

iOS, macOS, Linux, Windows

### Browser

Chrome, Safari, Safari iOS, Microsoft Edge, Firefox
