### ISSUE TITLE
[bug] `<rh-tab>` long text content should be constrained to 200px

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1864]
When we converted from a shadow button to a div internally we lost inherent styles that came with button.  This wasn't caught  outside of use case for long text content.

adding the following to `#button` in tab.css fixes the problem

```css
box-sizing: border-box;  /* [slot] { box-sizing: border-box; } instead maybe? *?
text-align: center;
```
