### ISSUE TITLE
[docs] Hide "Menu" from Elements list

### ISSUE THREAD

**Issue by adamjohnson** [RedHat-UX/red-hat-design-system#1980]
## Description

`<rh-menu>` should be hidden from the list of elements on uxdot because it leads to a 404. 

## Screenshots

![The menu link on the uxdot sidenav](https://github.com/user-attachments/assets/059149cb-7732-4441-b29f-1c70e39a131e)

## Additional context

```css
uxdot-sidenav-dropdown-menu-item[data-slug="menu"] {
    display: none;
}
```
