### ISSUE TITLE
`<rh-tile>` should default to setting a background of `lightest`

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#2023]
Initial report:

```
Michael Wells [Oct 18th at 11:17 AM]
new thing. rh-tile used to have a white bg as a default, it no longer does. is that purposeful?
```

Excerpt from `rh-tile.css`
```
https://github.com/RedHat-UX/red-hat-design-system/blob/33f88dab8e4a3f9e329c2fd3614e3363a3e00fc8/elements/rh-tile/rh-tile.css#L60-L65
```
Tile currently is only setting its background color when explicitly given a palette.  Otherwise it allows the background of whatever its placed on to bleed through (this could be bad for accessibility)

Question:
With the implementation of theming tokens, should tile set it's color-palette="lightest" if left undefined.

Excerpt from `rh-tile.ts`
https://github.com/RedHat-UX/red-hat-design-system/blob/33f88dab8e4a3f9e329c2fd3614e3363a3e00fc8/elements/rh-tile/rh-tile.ts#L127-L136

The comment, gives me pause.  Base was a concept we haven't implemented.  I'm assuming the code here was written to still fulfill this orphaned idea?  
> Tile always resets its context to `base`, unless explicitly provided with a `color-palette`. 

Should the fix be.  If `color-palette` is undefined set to `lightest`
```ts
  @colorContextProvider()
  @property({ reflect: true, attribute: 'color-palette' }) colorPalette: ColorPalette = lightest;
```

or in the css when `.light` or `.dark` gets set to the `#outer`

```css
  &.light {
    --rh-color-surface: var(--rh-color-surface-lightest, #ffffff);
  &.dark {
    --rh-color-surface: var(--rh-color-surface-darkest, #151515);
    --_focus-background-color:
      var(--rh-tile-focus-background-color,
        var(--rh-color-surface-darker, #1f1f1f));
    --_disabled-background-color:
      var(--rh-tile-disabled-background-color,
        var(--rh-color-surface-dark, #383838));
  }
  ```

and move that above the `& .palette-lightest - darkest` rules?

Doing the later will cause a tile to always appear "darkest" on a dark parent context, unless overridden by setting its own color-palette.
