### ISSUE TITLE
`rh-avatar` margin-bottom on `plain` variant

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#2149]
`rh-avatar` enforces a bottom margin when it is `layout="block"` or is in a mobile viewport:

```css
:host([layout='block']) :is(img, canvas, svg), 
#container.mobile :is(img, canvas, svg) {
    margin-block-end: var(--rh-space-lg, 16px);
}
```
@coreyvickery stated the avatar should have "No margins" for this variant.
