### ISSUE TITLE
[bug] <rh-footer> links should be styled to match dark context colors.

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#307]
### Describe the bug

Currently, the `<a>` tags are styled using the default color variables.  We need to change them to use the dark context color variables.

```css
.on-dark {
  --pfe-broadcasted--text: var(--pfe-theme--color--text--on-dark, #fff);
  --pfe-broadcasted--text--muted: var(--pfe-theme--color--text--muted--on-dark, #d2d2d2);
  --pfe-broadcasted--link: var(--pfe-theme--color--link--on-dark, #73bcf7);
  --pfe-broadcasted--link--hover: var(--pfe-theme--color--link--hover--on-dark, #bee1f4);
  --pfe-broadcasted--link--focus: var(--pfe-theme--color--link--focus--on-dark, #bee1f4);
  --pfe-broadcasted--link--visited: var(--pfe-theme--color--link--visited--on-dark, #bee1f4);
  --pfe-broadcasted--link-decoration: var(--pfe-theme--link-decoration--on-dark, none);
  --pfe-broadcasted--link-decoration--hover: var(--pfe-theme--link-decoration--hover--on-dark, underline);
  --pfe-broadcasted--link-decoration--focus: var(--pfe-theme--link-decoration--focus--on-dark, underline);
  --pfe-broadcasted--link-decoration--visited: var(--pfe-theme--link-decoration--visited--on-dark, none);
  --context: dark;
}
```

### Which Component?

rh-footer

### Steps to reproduce

1. `git fetch && checkout main`
2. `npm run dev`
3. Visit http://localhost:8000/demo/rh-footer/
4. The link in the first `rh-footer-block` is the wrong color

### Expected behaviour

rh-footer links should be styled using the dark context color variables

### Screenshots

![Screen Shot 2022-05-24 at 8 30 34 AM](https://user-images.githubusercontent.com/3428964/170056501-bf90b94c-d85b-45a1-a80b-c25f2fb84743.png)
