### ISSUE TITLE
[bug] footer: two column breakpoint on global footer not present

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#496]
On the lower menu, it looks like we’re missing a breakpoint that puts them into 2 columns. The live versions go from 3 down to 1.

## What I did

- added in a new 2 column for the primary-links in the global-footer view for one of the mobile breakpoints
- refactored and reordered the tokens to better align with the XD mockups
- added tests for checking grid and flex layouts for global-footer primary/secondary links at multiple breakpoints

## Code review

- https://github.com/RedHat-UX/red-hat-design-system/commit/e40662ea31c7a9d622f521b53067d59404b1d008

## Testing Instructions

1. Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/
2. Check that each of the following breakpoints match the correct grid column and flex layout per the [design specs](https://xd.adobe.com/view/835616bd-1374-483d-ab10-6ae92e0e343c-d605/screen/97d57a68-99ce-4d89-88de-63aa3d0ab325/)

Breakpoints:
- mobilePortraitBreakpoint = 320px
- mobileLandscapeBreakpoint = 576px
- tabletPortraitBreakpoint = 768px
- tabletLandscapeBreakpoint = 992px
- desktopSmallBreakpoint = 1200px
- desktopLargeBreakpoint = 1368px

## Screenshots

![deploy-preview-491--red-hat-design-system netlify app_components_footer_demo_(RHDC_ 6 desktopSmallBreakpoint)](https://user-images.githubusercontent.com/3428964/186676316-de8be841-5586-4ec2-8991-9daac0a9ad3c.png)
![deploy-preview-491--red-hat-design-system netlify app_components_footer_demo_(RHDC_ 5 tabletLandscapeBreakpoint)](https://user-images.githubusercontent.com/3428964/186676319-eb5c1519-45f3-4af0-afb0-c6f08607d22f.png)
![deploy-preview-491--red-hat-design-system netlify app_components_footer_demo_(RHDC_ 4 tabletPortraitBreakpoint)](https://user-images.githubusercontent.com/3428964/186676324-c868e131-2429-4893-884d-c45190c168ee.png)
![deploy-preview-491--red-hat-design-system netlify app_components_footer_demo_(RHDC_ 3 mobileBreakpoint)](https://user-images.githubusercontent.com/3428964/186676325-20372a98-7f67-4961-af4e-516d56a1cf5d.png)
![deploy-preview-491--red-hat-design-system netlify app_components_footer_demo_(RHDC_ 2 mobileLandscapeBreakpoint)](https://user-images.githubusercontent.com/3428964/186676330-93147333-b885-4344-9c0c-e35353206fb3.png)
![deploy-preview-491--red-hat-design-system netlify app_components_footer_demo_(RHDC_ 1 mobilePortraitBreakpoint)](https://user-images.githubusercontent.com/3428964/186676332-ea85ee47-8ed7-47af-bd26-10337444b50c.png)

## Current mitigations

```css
// Grid and layout fixes for global footer.
rh-global-footer::part(links-secondary) {
    grid-template-columns: 1fr;
}
rh-global-footer::part(links-primary) {
    display: grid;
    grid-template-columns: 1fr 1fr;
}
@media screen and (min-width: 601px) {
    rh-global-footer::part(links-secondary) {
        grid-template-columns: 1fr 1fr;
    }
}
@media screen and (min-width: 700px) {
    rh-global-footer::part(links-primary) {
        grid-template-columns: 1fr 1fr 1fr;
    }
}
@media screen and (min-width: 1008px) {
    rh-global-footer::part(links-primary) {
        display: flex;
    }
}
```
