### ISSUE TITLE
[bug] footer: tertiary slot in global footer has a margin-start padding that needs to be removed

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#498]
There is just a flat out erroneous extra margin on the tertiary slot that needs to be removed.  I'm not sure why it was there.

## What I did

- Removed margin-start for tertiary slot

## Code review

- [x] https://github.com/RedHat-UX/red-hat-design-system/issues/498

## Testing instructions

- Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/
- [x] On mobile width, ensure that the "Summit logo" is `32px` away from the "privacy policy statement above.

## Screenshots

<img width="1108" alt="Screen Shot 2022-08-25 at 9 43 10 AM" src="https://user-images.githubusercontent.com/3428964/186682494-3f131f48-9e45-4ebf-87b7-abd8c095f71a.png">

<img width="386" alt="Screen Shot 2022-08-25 at 9 48 10 AM" src="https://user-images.githubusercontent.com/3428964/186682511-8bca45bf-3e8a-4663-9709-3833b1a0a6ef.png">

## Current mitigations

```scss
// Hide extra margin on smaller device sizes for footer tertiary slot.
@media screen and (max-width: 1007px) {
    rh-global-footer::part(tertiary) {
        margin-block-start: 0;
    }
}
```
