### ISSUE TITLE
[bug] footer: max width on footer-block

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#524]
## What I did

- Added max-width to all children of `rh-footer-block`

## Code Review

- https://github.com/RedHat-UX/red-hat-design-system/commit/235657f6c26b043c183a5e1c6273cec5fcf93aac

## Testing

- Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/
- On desktop, zoom your browser out so it's super wide.
- [x] Ensure that the contents of the rh-footer-block to not extend `650px`

## Screenshots

![Screen Shot 2022-09-12 at 5 36 40 PM](https://user-images.githubusercontent.com/3428964/189763046-f4b48aee-f1ba-492e-90c3-fbd47fcded7f.png)

## Current mitigation

```css
// Add max-width to footer about section.
rh-footer-block::part(content) {
    max-width: 650px;
}
```
