### ISSUE TITLE
[bug] <rh-secondary-nav> logo and CTA font size

### ISSUE THREAD

**Issue by alypilkons-RH** [RedHat-UX/red-hat-design-system#589]
### Describe the bug

On at least some pages of redhat.com there is a file that sets this CSS property:

html {
  font-size: 62.5%;
}

This causes the logo and CTA in the secondary nav component to load very small (11.25px for the logo).

Steven figured out that this can be fixed with CSS for now (setting the logo font size to 1.8rem) but that ideally that CSS wouldn't be needed.

### Which Component?

rh-secondary-nav

### Steps to reproduce

Steven replicated the behavior in this codepen: https://codepen.io/zeroedin/pen/KKRYYzj

### Expected behaviour

Logo and CTA should be 18px by default without extra CSS

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by zeroedin** [comment]
As @alypilkons-RH pointed to with the Codepen link, at this time the fix for this issue is the following lightdom CSS overrides:

```css
rh-secondary-nav > [slot="logo"] {
  font-size: 1.8rem !important;
}

rh-secondary-nav > [slot="cta"] {
  --rh-font-size-text-xl: 1.6rem !important;
}
```

From what I understand, this issue is only in D7 instances and is caused by the following font-size rules:

```css
html {
  font-size: 62.5%
}
body {
  font-size: 1.6rem;
}
```

I'm also going to fix it internally to the component shadowdom CSS with:

```css 
:host {
  font-size: initial;
}

::slotted([slot="logo"]) {
  font-size: 1.125em !important;
}

::slotted([slot="cta"]) {
  --rh-font-size-text-xl: 1em !important;
}
```
This code had once existed in similar form but was refactored out by mistake.  It will be added back to the shadowdom css.

Adding the above styles will only fix the font-size issue **post** upgrade.  The lightdom overrides for D7 will still need to be added to avoid FOUC pre component upgrade.
