### ISSUE TITLE
[bug] <rh-alert> header slot font

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#889]
### Describe the bug

`<rh-alert>`'s header slot is using Red Hat Display instead of Red Hat Text on ux.redhat.com. I think it's pulling the font family from the site's heading styles.

### Which Component?

rh-alert

### Steps to reproduce

Check an [alert on the Call to Action page](https://ux.redhat.com/elements/call-to-action/#content) on ux.redhat.com

### Expected behaviour

The alert heading should be using Red Hat Text as its font family.

### Screenshots

![Screenshot 2023-04-04 at 9 04 12 AM](https://user-images.githubusercontent.com/95588923/229800493-5c8b0aa7-a1db-40a3-acea-04f8b6db8484.png)

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by zeroedin** [comment]
A fix that looks like it works is instead of setting the `--rh-font-family-heading` just set the `font-family` directly on line 82 of `rh-alert.css` https://github.com/RedHat-UX/red-hat-design-system/blob/0dde462911ebe9964c6c407166652e26f1d4318c/elements/rh-alert/rh-alert.css#L78-L83

fix:
```css
header ::slotted(:is(h1,h2,h3,h4,h5,h6)) {
  font-size: var(--rh-font-size-body-text-sm, 0.875rem) !important;
  margin: 0 !important;
  
  font-family: var(--_font-family) !important;
}
```
