### ISSUE TITLE
[docs] CSS cleanup

### ISSUE THREAD

**Issue by nikkimk** [RedHat-UX/red-hat-design-system#969]
### Description

Code tab of docs page needs some CSS cleanup.

### Suggested solution

Code tab of docs page should match this [XD file](https://xd.adobe.com/view/a7dfa813-450d-4100-98ce-5486fb30246b-f28c/)

**Comment by bennypowers** [comment]
here's some css which gets us most of the way there without changing any markup

```css
.api dd {
  margin-inline-start: 0;
}
.api .inline-type pre {
  display: inline-block;
  margin: 0;
  padding: 0;
}
.api dl.member dt:first-of-type::before,
.api dl.member dd:last-of-type::after {
  display: block;
  content: '';
  position: absolute;
  width: 100%;
  border-block-start: 1px solid black;
  inset-inline: 0;
}
.api dl.member dt:first-of-type::before {
    margin-block-start: -.5em;
}
.api dl.member dd:last-of-type::after {
    margin-block-end: -.5em;
}
.api dl.member {
  display: grid;
  grid-auto-flow: column;
  grid-template-rows: min-content 1fr;
  position: relative;
  margin-block: 1em;
}
```

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/33df96e2-4e56-4445-8343-61096325c1e8)
